apiVersion: v1
data:
  run.sh: |-
    @test "Testing MariaDB is accessible" {
      mysql -h my-site-mariadb -uroot -p$MARIADB_ROOT_PASSWORD -e 'show databases;'
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: my-site
  name: my-site-mariadb-tests
  namespace: web
