apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/instance: my-site
    chart: mariadb-7.3.11
    component: master
    heritage: Helm
    release: my-site
  name: my-site-mariadb
  namespace: web
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: mariadb
    component: master
    release: my-site
  type: ClusterIP
