apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: my-site-joomla
    app.kubernetes.io/instance: my-site
    chart: joomla-7.1.11
    heritage: Helm
    release: my-site
  name: my-site-joomla-joomla
  namespace: web
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
