apiVersion: v1
data:
  joomla-password: ++++++++
kind: Secret
metadata:
  labels:
    app: my-site-joomla
    app.kubernetes.io/instance: my-site
    chart: joomla-7.1.11
    heritage: Helm
    release: my-site
  name: my-site-joomla
  namespace: web
type: Opaque
