apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-site-joomla
    app.kubernetes.io/instance: my-site
    chart: joomla-7.1.11
    heritage: Helm
    release: my-site
  name: my-site-joomla
  namespace: web
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8081
      targetPort: http
    - name: https
      port: 4431
      targetPort: https
  selector:
    app: my-site-joomla
  type: NodePort
